export const el = {
  viewport: document.getElementById('viewport'),
  nodesLayer: document.getElementById('nodesLayer'),
  edgesSvg: document.getElementById('edges'),
  minimapSvg: document.getElementById('minimap'),
  runBtn: document.getElementById('runBtn'),
  status: document.getElementById('status'),
  apiBase: document.getElementById('apiBase'),
  query: document.getElementById('query'),
  finalContent: document.getElementById('finalContent'),
  nodePanel: document.getElementById('nodePanel'),
  nodePanelTitle: document.getElementById('nodePanelTitle'),
  nodeContent: document.getElementById('nodeContent'),
  closeNode: document.getElementById('closeNode'),
  fitBtn: document.getElementById('fitBtn'),
  zoomInBtn: document.getElementById('zoomInBtn'),
  zoomOutBtn: document.getElementById('zoomOutBtn'),
  hudFit: document.getElementById('hudFit'),
  hudZoomIn: document.getElementById('hudZoomIn'),
  hudZoomOut: document.getElementById('hudZoomOut'),
  runHistory: document.getElementById('runHistory'),
  nodeList: document.getElementById('nodeList'),
  palette: document.getElementById('palette'),
  paletteSearch: document.getElementById('paletteSearch'),
  paletteList: document.getElementById('paletteList'),
};
